#!/usr/bin/env python3
"""The PUBLIC API's record — the library half of the `--json` wire's contract.

`nml`'s libraries are consumed BY PATH and BY PINNED REV, never from
crates.io, so `cargo`'s own version resolution protects nobody: a removed
method, a reshaped enum variant or a new private field lands green here
and surfaces in the consumer, days later, as a compile error nothing
announced (one fold shipped three at once). The wire has a record, a
stamp and a ledger for exactly this reason; the API gets the same three.

* the RECORD  `docs/api/<crate>.api.txt` — every public item of every
  library crate, one line each, generated by `cargo public-api
  --simplified` (rustdoc's own view of the surface, so a re-export, a
  blanket impl or an inherited trait method is seen as the COMPILER sees
  it, never as a text scan guesses);
* the STAMP   `# apiVersion A, revision R` at the head of each record —
  `revision` +1 for an ADDITION (a line appears), `apiVersion` +1 for a
  BREAK (a line is gone or changed). One stamp for the workspace: the
  crates version together (`version.workspace = true`) and one consumer
  pins them together.
* the LEDGER  one CHANGELOG entry per stamp, naming what moved.

The gate: a record that drifted at an unchanged stamp fails; a stamp that
moved with no ledger entry fails; a REMOVED or CHANGED line at an
unchanged `apiVersion` fails, naming it. `NML_UPDATE_GOLDEN=1` rewrites
the records after the stamp moved — never before, and never by hand: it
is held to the SAME classification, so a regeneration records a decision
somebody made and can never stand in for making it.

Run: `just gate-api` (or `python3 scripts/api_record.py`). Needs
`cargo-public-api` on PATH; the CI job installs the pinned version. The
local fast loop gets the half that needs no tool — `nml-cli`'s
`out.rs`'s `api_contract` module, which holds the records, the stamp and
the ledger to each other on every `cargo test`.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RECORD_DIR = ROOT / "docs" / "api"
CHANGELOG = ROOT / "CHANGELOG.md"

# Every LIBRARY crate: `nml-cli` is a binary, and its surface is the CLI's
# own contract (`--json`, the wire record), not a Rust API.
CRATES = ["nml-core", "nml-validate", "nml-fmt", "nml-lsp"]

# The tool the record is generated by, pinned: rustdoc's JSON rendering
# moves with the toolchain, so the pair (toolchain, tool) is what makes a
# record reproducible. Bump both in one reviewed change.
TOOL_VERSION = "0.52.0"

HEADER = (
    "# The PUBLIC API's RECORD — GENERATED by scripts/api_record.py from "
    "`cargo public-api --simplified`: every public item of this crate, one line each,"
    " as rustdoc sees it. The stamp below is stated once: revision +1 for an ADDITION,"
    " apiVersion +1 for a BREAK (a line removed or changed). A change here at an"
    " unchanged stamp, a stamp without a CHANGELOG entry, or a break at an unchanged"
    " apiVersion fails the API gate; NML_UPDATE_GOLDEN=1 regenerates after the stamp"
    " moved — never edit by hand"
)
STAMP_RE = re.compile(r"^# apiVersion (\d+), revision (\d+)$")
# One CHANGELOG entry per stamp, the latest first — the API ledger.
LEDGER_RE = re.compile(r"^- \*\*public API apiVersion (\d+), revision (\d+)\.?\*\*", re.M)


def record_path(crate: str) -> Path:
    return RECORD_DIR / f"{crate}.api.txt"


def generate(crate: str) -> list[str]:
    """This crate's public items, as `cargo public-api` renders them."""
    proc = subprocess.run(
        [
            "cargo",
            "public-api",
            "--manifest-path",
            str(ROOT / "crates" / crate / "Cargo.toml"),
            "--simplified",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(
            f"cargo public-api failed for {crate} ({proc.returncode}):\n{proc.stderr[-2000:]}"
        )
    return [line for line in proc.stdout.splitlines() if line.strip()]


def parse(path: Path) -> tuple[tuple[int, int] | None, list[str]]:
    """(the record's stamp, its item lines); the stamp is None when the
    record carries none."""
    if not path.is_file():
        return None, []
    return parse_text(path.read_text(encoding="utf-8"))


def parse_text(text: str) -> tuple[tuple[int, int] | None, list[str]]:
    """[`parse`] over the record's TEXT, so the self-test reads a record
    the same way the gate does."""
    stamp: tuple[int, int] | None = None
    lines: list[str] = []
    for line in text.splitlines():
        if m := STAMP_RE.fullmatch(line):
            stamp = (int(m[1]), int(m[2]))
        elif line.startswith("# ") or not line.strip():
            # `# ` is this file's own prose. An API line may START with
            # `#`: `cargo public-api` renders an attribute that is part
            # of the contract (`#[non_exhaustive] pub enum …`), and
            # dropping those hid eleven items from the record.
            continue
        else:
            lines.append(line)
    return stamp, lines


def render(stamp: tuple[int, int], lines: list[str]) -> str:
    return f"{HEADER}\n# apiVersion {stamp[0]}, revision {stamp[1]}\n" + "".join(
        f"{line}\n" for line in lines
    )


# `pub some::path::Struct::field: Type` — a struct's or a variant's FIELD,
# as `cargo public-api` renders it (no `fn`, no `impl`, a `:` type).
FIELD_RE = re.compile(r"^pub (?P<owner>[A-Za-z0-9_:]+)::(?P<field>[A-Za-z0-9_]+): ")


def additions_only(old: list[str], new: list[str]) -> str | None:
    """None when `new` only ADDS to `old`; else the first item that moved
    the other way — which is `apiVersion`'s business, never the
    revision's. Lines are compared as a SET: `cargo public-api` sorts
    its output, so an item's position carries nothing.

    Two shapes are breaking, and the second is the one a naive set-diff
    reads as additive: a line that is GONE (a removal, a rename, a
    reshaped variant), and a new public FIELD on a type that already
    existed — which stops every exhaustive struct literal and every
    exhaustive pattern downstream, though nothing was removed.

    What this CANNOT see, measured: a new PRIVATE field on a public
    struct. It removes nothing and adds no public item, so every line
    here is byte-identical, while downstream the struct stops being
    constructible (`ast::Arm` did exactly this). The classifier names that one
    (`cargo-semver-checks`, `constructible_struct_adds_private_field`),
    which is why `just gate-api` and the CI job run both.
    """
    gone = sorted(set(old) - set(new))
    if gone:
        return f"`{gone[0]}` is gone"
    owners = {
        m.group("owner")
        for line in old
        if (m := FIELD_RE.match(line))
    }
    for line in sorted(set(new) - set(old)):
        m = FIELD_RE.match(line)
        if m and m.group("owner") in owners:
            return (
                f"`{line}` is a NEW PUBLIC FIELD on `{m.group('owner')}`, which already had "
                "public fields — every exhaustive literal and pattern downstream stops compiling"
            )
    return None


def stamp_decision(
    stamp: tuple[int, int],
    was_stamp: tuple[int, int],
    was: list[str],
    now: list[str],
) -> str | None:
    """The verdict a REGENERATION must not paper over, for one crate:
    `None` when the record may be rewritten at `stamp`, else the sentence
    saying which decision is still owed. Pure, so the self-test can drive
    it — and shared by both paths, because `NML_UPDATE_GOLDEN=1` is the
    command every one of these sentences ends with: a regeneration that
    skipped the classification would ACCEPT the change it was asked to
    record, and every later run would be green with no stamp moved and
    no ledger entry naming it (measured: an addition and a REMOVAL both
    landed that way)."""
    if was == now:
        return None
    broke = additions_only(was, now)
    if broke and stamp[0] == was_stamp[0]:
        return (
            f"a BREAKING API change at an unchanged apiVersion ({was_stamp[0]}) — {broke}. "
            "Bump apiVersion, add the CHANGELOG entry naming the break, then "
            "NML_UPDATE_GOLDEN=1 python3 scripts/api_record.py"
        )
    if not broke and stamp == was_stamp:
        added = sorted(set(now) - set(was))
        return (
            f"the public API GREW at an unchanged revision ({was_stamp[1]}) — "
            f"{len(added)} item(s), first `{added[0]}`. Bump revision, add the CHANGELOG "
            "entry, then NML_UPDATE_GOLDEN=1 python3 scripts/api_record.py"
        )
    return None


def api_check_self_test() -> str | None:
    """The classifier must BITE before it is trusted, exactly as the wire's
    does (`docs_test.py` `wire_check_self_test`). An identical surface and a
    pure addition are additions; a line that is GONE and a new PUBLIC FIELD on
    a type that already had them are not — the second is the one a set-diff
    reads as additive, and it is the one that stopped every exhaustive literal
    downstream (`ast::Arm`). Returns None when the helpers behave, else what
    they got wrong."""
    base = [
        "pub struct nml_core::ast::Arm",
        "pub nml_core::ast::Arm::selector: Selector",
        "#[non_exhaustive] pub enum nml_core::ast::Target",
    ]
    cases: list[tuple[list[str], str | None]] = [
        (base, None),
        # a whole new item, and a new type WITH fields: nothing downstream
        # was exhaustive over a type that did not exist.
        (base + ["pub fn nml_core::ast::Arm::target(&self) -> &Target"], None),
        (base + ["pub struct nml_core::ast::Lit", "pub nml_core::ast::Lit::v: u8"], None),
        (base[:1] + base[2:], "is gone"),
        (base + ["pub nml_core::ast::Arm::target: Target"], "NEW PUBLIC FIELD"),
        # a reshape is a removal plus an addition; the removal is what it is.
        ([base[0], "pub nml_core::ast::Arm::selector: Other", base[2]], "is gone"),
    ]
    for new, expect in cases:
        verdict = additions_only(base, new)
        if expect is None and verdict is not None:
            return f"an addition was refused: {verdict}"
        if expect is not None and (verdict is None or expect not in verdict):
            return f"a non-addition passed or was misnamed: {new} -> {verdict!r}"
    # The DECISION the regeneration is held to — the rule that was
    # skipped under NML_UPDATE_GOLDEN=1 and let an addition and a
    # removal through. Driven directly, both ways, at a moved stamp and
    # at an unmoved one.
    grew = base + ["pub fn nml_core::ast::Arm::target(&self) -> &Target"]
    shrank = base[:1] + base[2:]
    decisions: list[tuple[tuple[int, int], tuple[int, int], list[str], str | None]] = [
        # unchanged: nothing is owed
        ((4, 1), (4, 1), base, None),
        # an addition at an unchanged stamp, and the same after revision +1
        ((4, 1), (4, 1), grew, "GREW at an unchanged revision"),
        ((4, 2), (4, 1), grew, None),
        # a break at an unchanged apiVersion, and the same after +1
        ((4, 1), (4, 1), shrank, "BREAKING API change"),
        ((5, 1), (4, 1), shrank, None),
    ]
    for stamp, was_stamp, now, expect in decisions:
        verdict = stamp_decision(stamp, was_stamp, base, now)
        if expect is None and verdict is not None:
            return f"a reviewed stamp was refused: {stamp} over {was_stamp}: {verdict}"
        if expect is not None and (verdict is None or expect not in verdict):
            return f"a decision was skipped or misnamed: {stamp} over {was_stamp} -> {verdict!r}"
    # The record's own round trip, including the shape that hid eleven items
    # when it was read as prose: an API line may START with `#`.
    rendered = render((7, 2), base)
    stamp, lines = parse_text(rendered)
    if stamp != (7, 2) or lines != base:
        return f"a record does not survive render -> parse: {stamp} {lines}"
    return None


# The ONE source of the stamp, as `out.rs` REVISION is the wire's: the
# record carries the stamp it was GENERATED at, so the two together say
# whether the surface moved since the last reviewed stamp.
STAMP_SOURCE = "nml-cli/src/out.rs"
STAMP_DECL_RE = re.compile(r"pub const API_STAMP: \(u32, u32\) = \((\d+), (\d+)\);")


def declared_stamp() -> tuple[int, int]:
    text = (ROOT / STAMP_SOURCE).read_text(encoding="utf-8")
    m = STAMP_DECL_RE.search(text)
    if not m:
        raise SystemExit(f"{STAMP_SOURCE} declares no `pub const API_STAMP: (u32, u32)`")
    return (int(m[1]), int(m[2]))


def ledger_stamps() -> list[tuple[int, int]]:
    text = CHANGELOG.read_text(encoding="utf-8")
    return [(int(a), int(r)) for a, r in LEDGER_RE.findall(text)]


def ledger_problem(stamp: tuple[int, int]) -> str:
    return (
        f"CHANGELOG.md names no `**public API apiVersion {stamp[0]}, revision {stamp[1]}**` "
        "entry — a stamp moves WITH the sentence that says what moved"
    )


def check() -> list[str]:
    update = "NML_UPDATE_GOLDEN" in os.environ
    problems: list[str] = []
    RECORD_DIR.mkdir(parents=True, exist_ok=True)

    # A gate whose verdict function is wrong is a gate about nothing, and
    # this one's verdict is the whole contract — it runs first, every time.
    if (broken := api_check_self_test()) is not None:
        return [f"the classifier's self-test failed: {broken}"]

    stamp = declared_stamp()
    # Generated ONCE: `cargo public-api` is the expensive half, and both
    # paths below read the same surface.
    generated = {crate: generate(crate) for crate in CRATES}
    recorded = {crate: parse(record_path(crate)) for crate in CRATES}
    # The decisions still owed, by the SAME rule under regeneration as
    # under a plain run.
    owed = {
        crate: stamp_decision(stamp, was_stamp, was, generated[crate])
        for crate, (was_stamp, was) in recorded.items()
        if was_stamp is not None
    }
    if update:
        # A regeneration records a reviewed change; it never MAKES the
        # review. Refuse while a decision is owed.
        if problems := [
            f"{record_path(crate).relative_to(ROOT)}: {why}"
            for crate, why in sorted(owed.items())
            if why is not None
        ]:
            return problems
        # EVERY record is rewritten at the declared stamp, not only the
        # ones whose text moved: the stamp in a record is the stamp its
        # surface was last REVIEWED at, and a workspace has one.
        for crate in CRATES:
            record_path(crate).write_text(render(stamp, generated[crate]), encoding="utf-8")
        return [] if stamp in ledger_stamps() else [ledger_problem(stamp)]
    stamps = {crate: recorded[crate][0] for crate in CRATES}
    present = {s for s in stamps.values() if s is not None}
    if len(present) > 1:
        return [f"the records carry different stamps: {sorted(present)} — one stamp per workspace"]
    # The records are stamped by the ONE source, whether or not the
    # surface moved: a record carrying a stamp `out.rs` does not declare
    # was hand-edited, and a hand-edited stamp is how a break would pass
    # as reviewed.
    if present and present != {stamp}:
        was = present.pop()
        return [
            f"the records are stamped {was}, the ONE source ({STAMP_SOURCE} API_STAMP) says "
            f"{stamp} — regenerate with NML_UPDATE_GOLDEN=1 after the stamp and its CHANGELOG "
            "entry moved, never by hand"
        ] + ([] if stamp in ledger_stamps() else [ledger_problem(stamp)])

    for crate in CRATES:
        path = record_path(crate)
        was_stamp, was = recorded[crate]
        now = generated[crate]
        if was_stamp is not None and was == now:
            continue
        if was_stamp is None:
            problems.append(f"{path.relative_to(ROOT)} does not exist — the crate has no record")
            continue
        if (why := owed[crate]) is not None:
            problems.append(f"{path.relative_to(ROOT)}: {why}")
            continue
        problems.append(
            f"{path.relative_to(ROOT)} drifted — NML_UPDATE_GOLDEN=1 "
            "python3 scripts/api_record.py rewrites it"
        )

    if stamp not in ledger_stamps():
        problems.append(ledger_problem(stamp))
    return problems


def main() -> int:
    problems = check()
    for p in problems:
        print(f"FAIL {p}")
    total = sum(len(parse(record_path(c))[1]) for c in CRATES)
    stamp = declared_stamp()
    print(
        f"api-record: {len(CRATES)} crates, {total} public items, "
        f"stamp {'apiVersion %d, revision %d' % stamp if stamp else 'MISSING'}, "
        f"{len(ledger_stamps())} ledger entries"
    )
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
